name: spider
description: A small dart command-line tool for generating dart references of assets from the assets folder.
version: 2.0.0
homepage: https://github.com/BirjuVachhani/spider

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  yaml: ^3.1.0
  args: ^2.1.0
  dart_style: ^2.0.1
  logging: ^1.0.1
  watcher: ^1.0.0
  http: ^0.13.2
  html: ^0.15.0
  sprintf: ^6.0.0
  meta: ^1.7.0

dev_dependencies:
  build_runner: ^2.0.1
  build_version: ^2.0.3
  test: ^1.17.3
  lints: ^1.0.1
  mockito: ^5.0.16

executables:
  spider: main