name: Update Formula

on:
  workflow_dispatch:

jobs:
  update_formula:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set env
        run: export GIT_TAG=`git describe --tags --abbrev=0`
      - name: Update Formula
        run: |
          export SPIDER_URL="https://github.com/BirjuVachhani/spider/archive/refs/tags/$GIT_TAG.tar.gz"
          curl -L -o spider.tar.gz "$SPIDER_URL"
          export SPIDER_SHA=`sha256sum spider.tar.gz | cut -d' ' -f1`
          cat spider.rb | sed -e "s/url \".*\"/url \"$SPIDER_URL\"/g" -e "s/sha256 \".*\"/sha256 \"$SPIDER_SHA\"/g" >> spider.rb
          git config user.name github-actions
          git config user.email github-actions@github.com
          echo "================================================================"
          echo "Updated Formula:"
          cat spider.rb
          echo "================================================================"

          
      

