name: Build

on:
  push:
    paths:
      - '**.dart'
      - '**.yaml'
      - '**.yml'
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: dart pub get
      - name: Code Formatting
        run: dart format --set-exit-if-changed .
      - name: Build & Install Locally
        run: dart pub global activate --source path .
      - name: Check Publish Warnings
        run: dart pub publish --dry-run