name: Tests

on:
  push:
    paths:
      - '**.dart'
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  tests_and_coverage:
    runs-on: macos-latest
    steps:
      - uses: dart-lang/setup-dart@v1
      - name: Dart SDK
        run: dart --version
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: dart pub get
      - name: Activate Test Coverage
        run: dart pub global activate test_coverage
      - name: Run Tests & Generate Coverage
        run: dart pub global run test_coverage .
      - uses: codecov/codecov-action@v1
        with:
          file: coverage/lcov.info